### ISSUE TITLE
Files aren't being written to disk on server

### ISSUE THREAD

**Issue by tylerjw** [rexroni/blackjay#2]
When testing with the server it appears to receive the zip files just fine but nothing is copied to disk.

**Comment by rexroni** [comment]
Which operating system?  I am having trouble reproducing this.

Are you looking at an empty sync?  Syncs now happen on timed intervals if nothing needs to be synced.

**Comment by tylerjw** [comment]
I'm having this problem with my mac sending files i put in the folder to the server.

**Comment by rexroni** [comment]
try commenting out the cleanup_server_temp_files() function and see if you can manually unzip the zip file after the synchronization finishes.

**Comment by tylerjw** [comment]
I will try that but I think this might shed some light on the problem:

```
send_file: file size: 6273
Traceback (most recent call last):
  File "server.py", line 108, in run
    make_server_updates_live(push,UID)
  File "server.py", line 49, in make_server_updates_live
    os.rename('.blackjay/c2s'+UID+'/'+name,name)
FileNotFoundError: [Errno 2] No such file or directory: '.blackjay/c2scfc08c5c-0a3b-4d39-b4fc-7fb926a7c91e/./weaveringrally_blog/temp' -> './weaveringrally_blog/temp'
```

**Comment by tylerjw** [comment]
The zip files are extracting correctly... if I cd into the directory `.blackjay/c2scfc08c5c-0a3b-4d39-b4fc-7fb926a7c91e` I see this content:

```
$ ll
total 40K
drwxr-xr-x  5 blackjay 4.0K Mar  2 23:58  .
drwxr-xr-x 52 blackjay  12K Mar  2 23:58  ..
-rw-r--r--  1 blackjay 8.1K Mar  2 23:58  .DS_Store
drwxr-xr-x  2 blackjay 4.0K Mar  2 23:58  .blackjay
drwxr-xr-x  2 blackjay 4.0K Mar  2 23:58 'Badass Chicken'
drwxr-xr-x  2 blackjay 4.0K Mar  2 23:58  weaveringrally_blog
```
The problem is the relative path `/./` it is somehow inserting into the path after that... in other words, we might have to write our own version of the path join thing for this.

**Comment by rexroni** [comment]
Ah, ya the issue arises with directories.  I will investigate...

Got it.  I think is how the files are moved from temp directory to be live.  There is a missing step that checks that the target folder exists.  I can fix it tonight, or if you would like to, it would probably involve recursive calls to os.path.split().
